WFTH_SHOPIFY_SHOP_NAME = ENV['WFTH_SHOPIFY_SHOP_NAME'] || 'wfth'
WFTH_PERMISSIONS_SHOPIFY_COLLECTOR_API_KEY = ENV['WFTH_PERMISSIONS_SHOPIFY_COLLECTOR_API_KEY']
WFTH_PERMISSIONS_SHOPIFY_COLLECTOR_PASSWORD = ENV['WFTH_PERMISSIONS_SHOPIFY_COLLECTOR_PASSWORD']
